"""initial migration

Revision ID: 5e4adf563fb3
Revises:
Create Date: 2026-03-02 11:23:03.086357

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5e4adf563fb3"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "face_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.String(), nullable=False),
        sa.Column("employee_id", sa.String(), nullable=False),
        sa.Column("external_image_id", sa.String(), nullable=True),
        sa.Column("aws_collection_id", sa.String(), nullable=False),
        sa.Column("aws_image_id", sa.String(), nullable=False),
        sa.Column("aws_face_id", sa.String(), nullable=False),
        sa.Column("image_url", sa.String(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("meta_data", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_face_records_aws_collection_id"),
        "face_records",
        ["aws_collection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_face_records_aws_face_id"),
        "face_records",
        ["aws_face_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_face_records_aws_image_id"),
        "face_records",
        ["aws_image_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_face_records_company_id"), "face_records", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_face_records_employee_id"),
        "face_records",
        ["employee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_face_records_external_image_id"),
        "face_records",
        ["external_image_id"],
        unique=False,
    )
    op.create_index(op.f("ix_face_records_id"), "face_records", ["id"], unique=True)
    op.create_table(
        "liveness_results",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("face_id", sa.String(), nullable=True),
        sa.Column("image_id", sa.String(), nullable=True),
        sa.Column("recognition_confidence", sa.Float(), nullable=True),
        sa.Column("similarity", sa.Float(), nullable=True),
        sa.Column("match_count", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_liveness_results_face_id"),
        "liveness_results",
        ["face_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_liveness_results_id"), "liveness_results", ["id"], unique=True
    )
    op.create_index(
        op.f("ix_liveness_results_image_id"),
        "liveness_results",
        ["image_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_liveness_results_session_id"),
        "liveness_results",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_liveness_results_user_id"),
        "liveness_results",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_liveness_results_user_id"), table_name="liveness_results")
    op.drop_index(op.f("ix_liveness_results_session_id"), table_name="liveness_results")
    op.drop_index(op.f("ix_liveness_results_image_id"), table_name="liveness_results")
    op.drop_index(op.f("ix_liveness_results_id"), table_name="liveness_results")
    op.drop_index(op.f("ix_liveness_results_face_id"), table_name="liveness_results")
    op.drop_table("liveness_results")
    op.drop_index(op.f("ix_face_records_id"), table_name="face_records")
    op.drop_index(op.f("ix_face_records_external_image_id"), table_name="face_records")
    op.drop_index(op.f("ix_face_records_employee_id"), table_name="face_records")
    op.drop_index(op.f("ix_face_records_company_id"), table_name="face_records")
    op.drop_index(op.f("ix_face_records_aws_image_id"), table_name="face_records")
    op.drop_index(op.f("ix_face_records_aws_face_id"), table_name="face_records")
    op.drop_index(op.f("ix_face_records_aws_collection_id"), table_name="face_records")
    op.drop_table("face_records")
    # ### end Alembic commands ###
